// <auto-generated />
using System;
using FairwayFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FairwayFinder.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330010821_AddShotTable")]
    partial class AddShotTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FairwayFinder.Data.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CourseId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ClubName")
                        .HasColumnType("text")
                        .HasColumnName("club_name");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("CourseId")
                        .HasName("course_pkey");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.GolfCourseApiCourseMap", b =>
                {
                    b.Property<long>("GolfCourseApiCourseMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("golf_course_api_course_map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GolfCourseApiCourseMapId"));

                    b.Property<int>("ApiCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("api_course_id");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.HasKey("GolfCourseApiCourseMapId")
                        .HasName("golf_course_api_course_map_pkey");

                    b.HasIndex("ApiCourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_golf_course_api_course_map_api_course_id");

                    b.HasIndex("CourseId");

                    b.ToTable("golf_course_api_course_map", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Hole", b =>
                {
                    b.Property<long>("HoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("hole_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HoleId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<int>("Handicap")
                        .HasColumnType("integer")
                        .HasColumnName("handicap");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("hole_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Par")
                        .HasColumnType("integer")
                        .HasColumnName("par");

                    b.Property<long>("TeeboxId")
                        .HasColumnType("bigint")
                        .HasColumnName("teebox_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<int>("Yardage")
                        .HasColumnType("integer")
                        .HasColumnName("yardage");

                    b.HasKey("HoleId")
                        .HasName("hole_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeeboxId");

                    b.ToTable("hole", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.HoleStat", b =>
                {
                    b.Property<long>("HoleStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("hole_stats_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HoleStatsId"));

                    b.Property<bool?>("ApproachShotOb")
                        .HasColumnType("boolean")
                        .HasColumnName("approach_shot_ob");

                    b.Property<int?>("ApproachYardage")
                        .HasColumnType("integer")
                        .HasColumnName("approach_yardage");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool?>("HitFairway")
                        .HasColumnType("boolean")
                        .HasColumnName("hit_fairway");

                    b.Property<bool?>("HitGreen")
                        .HasColumnType("boolean")
                        .HasColumnName("hit_green");

                    b.Property<long>("HoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("hole_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("MissFairwayType")
                        .HasColumnType("bigint")
                        .HasColumnName("miss_fairway_type");

                    b.Property<long?>("MissGreenType")
                        .HasColumnType("bigint")
                        .HasColumnName("miss_green_type");

                    b.Property<short?>("NumberOfPutts")
                        .HasColumnType("smallint")
                        .HasColumnName("number_of_putts");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("score_id");

                    b.Property<bool?>("TeeShotOb")
                        .HasColumnType("boolean")
                        .HasColumnName("tee_shot_ob");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("HoleStatsId")
                        .HasName("hole_stats_pkey");

                    b.HasIndex("HoleId");

                    b.HasIndex("MissFairwayType");

                    b.HasIndex("MissGreenType");

                    b.HasIndex("RoundId");

                    b.HasIndex("ScoreId");

                    b.ToTable("hole_stats", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.MissType", b =>
                {
                    b.Property<long>("MissTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("miss_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MissTypeId"));

                    b.Property<string>("MissType1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("miss_type");

                    b.HasKey("MissTypeId")
                        .HasName("miss_type_pkey");

                    b.ToTable("miss_type", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Round", b =>
                {
                    b.Property<long>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoundId"));

                    b.Property<bool>("BackNine")
                        .HasColumnType("boolean")
                        .HasColumnName("back_nine");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<DateOnly>("DatePlayed")
                        .HasColumnType("date")
                        .HasColumnName("date_played");

                    b.Property<bool>("ExcludeFromStats")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_stats");

                    b.Property<bool>("FrontNine")
                        .HasColumnType("boolean")
                        .HasColumnName("front_nine");

                    b.Property<bool>("FullRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("full_round");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("ScoreIn")
                        .HasColumnType("integer")
                        .HasColumnName("score_in");

                    b.Property<int>("ScoreOut")
                        .HasColumnType("integer")
                        .HasColumnName("score_out");

                    b.Property<long>("TeeboxId")
                        .HasColumnType("bigint")
                        .HasColumnName("teebox_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("'unknown'::text");

                    b.Property<bool>("UsingHoleStats")
                        .HasColumnType("boolean")
                        .HasColumnName("using_hole_stats");

                    b.Property<bool>("UsingShotTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("using_shot_tracking");

                    b.HasKey("RoundId")
                        .HasName("round_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeeboxId");

                    b.ToTable("round", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.RoundStat", b =>
                {
                    b.Property<long>("RoundStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("round_stats_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoundStatsId"));

                    b.Property<int>("Birdies")
                        .HasColumnType("integer")
                        .HasColumnName("birdies");

                    b.Property<int>("Bogies")
                        .HasColumnType("integer")
                        .HasColumnName("bogies");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<int>("DoubleBogies")
                        .HasColumnType("integer")
                        .HasColumnName("double_bogies");

                    b.Property<int>("DoubleEagles")
                        .HasColumnType("integer")
                        .HasColumnName("double_eagles");

                    b.Property<int>("Eagles")
                        .HasColumnType("integer")
                        .HasColumnName("eagles");

                    b.Property<int>("HoleInOne")
                        .HasColumnType("integer")
                        .HasColumnName("hole_in_one");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Pars")
                        .HasColumnType("integer")
                        .HasColumnName("pars");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<int>("TripleOrWorse")
                        .HasColumnType("integer")
                        .HasColumnName("triple_or_worse");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("RoundStatsId")
                        .HasName("round_stats_pkey");

                    b.HasIndex("RoundId");

                    b.ToTable("round_stats", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Score", b =>
                {
                    b.Property<long>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("score_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScoreId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<long>("HoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("hole_id");

                    b.Property<short>("HoleScore")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_score");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("ScoreId")
                        .HasName("score_pkey");

                    b.HasIndex("HoleId");

                    b.HasIndex("RoundId");

                    b.ToTable("score", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Shot", b =>
                {
                    b.Property<long>("ShotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("shot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShotId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<int?>("EndDistance")
                        .HasColumnType("integer")
                        .HasColumnName("end_distance");

                    b.Property<string>("EndDistanceUnit")
                        .HasColumnType("text")
                        .HasColumnName("end_distance_unit");

                    b.Property<int?>("EndLie")
                        .HasColumnType("integer")
                        .HasColumnName("end_lie");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PenaltyStrokes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("penalty_strokes");

                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("score_id");

                    b.Property<int>("ShotNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shot_number");

                    b.Property<int>("StartDistance")
                        .HasColumnType("integer")
                        .HasColumnName("start_distance");

                    b.Property<string>("StartDistanceUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_distance_unit");

                    b.Property<int>("StartLie")
                        .HasColumnType("integer")
                        .HasColumnName("start_lie");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("ShotId")
                        .HasName("shot_pkey");

                    b.HasIndex("ScoreId")
                        .HasDatabaseName("ix_shot_score_id");

                    b.ToTable("shot", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Teebox", b =>
                {
                    b.Property<long>("TeeboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("teebox_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TeeboxId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsNineHole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nine_hole");

                    b.Property<bool>("IsWomens")
                        .HasColumnType("boolean")
                        .HasColumnName("is_womens");

                    b.Property<int>("Par")
                        .HasColumnType("integer")
                        .HasColumnName("par");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<int>("Slope")
                        .HasColumnType("integer")
                        .HasColumnName("slope");

                    b.Property<string>("TeeboxName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teebox_name");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<int>("YardageIn")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_in");

                    b.Property<int>("YardageOut")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_out");

                    b.Property<int>("YardageTotal")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_total");

                    b.HasKey("TeeboxId")
                        .HasName("teebox_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("teebox", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrCourseMap", b =>
                {
                    b.Property<long>("TgtrCourseMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tgtr_course_map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TgtrCourseMapId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("TgtrCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("tgtr_course_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("TgtrCourseMapId")
                        .HasName("tgtr_course_map_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("tgtr_course_map", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrPlayerMap", b =>
                {
                    b.Property<long>("TgtrPlayerMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tgtr_player_map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TgtrPlayerMapId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("TgtrPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("tgtr_player_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("TgtrPlayerMapId")
                        .HasName("tgtr_player_map_pkey");

                    b.ToTable("tgtr_player_map", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrRoundMap", b =>
                {
                    b.Property<long>("TgtrRoundMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tgtr_round_map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TgtrRoundMapId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<int>("TgtrRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("tgtr_round_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("TgtrRoundMapId")
                        .HasName("tgtr_round_map_pkey");

                    b.HasIndex("RoundId");

                    b.ToTable("tgtr_round_map", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrTeeboxMap", b =>
                {
                    b.Property<long>("TgtrTeeboxMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tgtr_teebox_map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TgtrTeeboxMapId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("TeeboxId")
                        .HasColumnType("bigint")
                        .HasColumnName("teebox_id");

                    b.Property<int>("TgtrCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("tgtr_course_id");

                    b.Property<int>("TgtrTeeboxId")
                        .HasColumnType("integer")
                        .HasColumnName("tgtr_teebox_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("TgtrTeeboxMapId")
                        .HasName("tgtr_teebox_map_pkey");

                    b.HasIndex("TeeboxId");

                    b.ToTable("tgtr_teebox_map", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.UserInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ClaimedOn")
                        .HasColumnType("date")
                        .HasColumnName("claimed_on");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<string>("InvitationIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invitation_identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SentByUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sent_by_user");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sent_to_email");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("user_invitation_pkey");

                    b.ToTable("user_invitation", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.UserProfile", b =>
                {
                    b.Property<long>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserProfileId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<Guid>("PublicIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("public_identifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("UserProfileId")
                        .HasName("user_profile_pkey");

                    b.HasIndex("PublicIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profile_public_identifier");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profile_user_id");

                    b.ToTable("user_profile", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.GolfCourseApiCourseMap", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Hole", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Data.Entities.Teebox", "Teebox")
                        .WithMany()
                        .HasForeignKey("TeeboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teebox");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.HoleStat", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Hole", "Hole")
                        .WithMany()
                        .HasForeignKey("HoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Data.Entities.MissType", "MissFairwayMissType")
                        .WithMany()
                        .HasForeignKey("MissFairwayType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FairwayFinder.Data.Entities.MissType", "MissGreenMissType")
                        .WithMany()
                        .HasForeignKey("MissGreenType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FairwayFinder.Data.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Data.Entities.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hole");

                    b.Navigation("MissFairwayMissType");

                    b.Navigation("MissGreenMissType");

                    b.Navigation("Round");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Round", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Data.Entities.Teebox", "Teebox")
                        .WithMany()
                        .HasForeignKey("TeeboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teebox");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.RoundStat", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Score", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Hole", "Hole")
                        .WithMany()
                        .HasForeignKey("HoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Data.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hole");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Shot", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Score");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.Teebox", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrCourseMap", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrRoundMap", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("FairwayFinder.Data.Entities.TgtrTeeboxMap", b =>
                {
                    b.HasOne("FairwayFinder.Data.Entities.Teebox", "Teebox")
                        .WithMany()
                        .HasForeignKey("TeeboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teebox");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FairwayFinder.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FairwayFinder.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FairwayFinder.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FairwayFinder.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
